server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # --- Datasource ---
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/bibliotech_catalogue
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  # --- JPA / Hibernate ---
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # --- Broker (Bus) ---
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

# --- Discovery ---
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

# --- Monitoring ---
management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

# --- Custom Info ---
info:
  app:
    name: "catalogue"
    description: "catalogue service"
    version: "1.0"

# --- Logs ---
logging:
  level:
    root: INFO
    org.hibernate.type.descriptor.sql: TRACE

build:
  version: "1.0"

catalogue:
  message: "Welcome to Library catalogue related local (dev) APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

build:
  version: "2.0"

catalogue:
  message: "Welcome to Library catalogue related QA APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
